-- Generated from generator/demo_specs/aws-vietnam-textile-supply-chain.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-textile-supply-chain
-- This is the schema that is actually deployed for VIETNAM_TEXTILE_SUPPLY_CHAIN.

-- Alerts fire on the bottom tail of Fabric On-Time
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_FABRIC_ON_TIME) AS T
  FROM RAW.FABRIC_SHIPMENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_FABRIC_ON_TIME <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_FABRIC_ON_TIME), 2) AS AVG_FABRIC_ON_TIME,
  ROUND(AVG(f.KPI_LEAD_TIME_AVG), 2) AS AVG_LEAD_TIME,
  ROUND(AVG(f.KPI_INVENTORY_DAYS), 2) AS AVG_INVENTORY_DAYS,
  ROUND(AVG(f.KPI_FABRIC_UTILIZATION), 2) AS AVG_FABRIC_UTILIZATION,
  ROUND(AVG(f.KPI_TRIM_AVAILABILITY), 2) AS AVG_TRIM_AVAILABILITY,
  ROUND(AVG(f.KPI_IMPORT_DEPENDENCY), 2) AS AVG_IMPORT_DEPENDENCY
FROM RAW.FABRIC_SHIPMENTS f
JOIN RAW.SUPPLIERS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_FABRIC_ON_TIME), 2) AS AVG_FABRIC_ON_TIME,
  ROUND(AVG(f.KPI_LEAD_TIME_AVG), 2) AS AVG_LEAD_TIME,
  ROUND(AVG(f.KPI_INVENTORY_DAYS), 2) AS AVG_INVENTORY_DAYS,
  ROUND(AVG(f.KPI_FABRIC_UTILIZATION), 2) AS AVG_FABRIC_UTILIZATION,
  ROUND(AVG(f.KPI_TRIM_AVAILABILITY), 2) AS AVG_TRIM_AVAILABILITY,
  ROUND(AVG(f.KPI_IMPORT_DEPENDENCY), 2) AS AVG_IMPORT_DEPENDENCY
FROM RAW.FABRIC_SHIPMENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_FABRIC_ON_TIME) AS KPI_FABRIC_ON_TIME, AVG(KPI_LEAD_TIME_AVG) AS KPI_LEAD_TIME_AVG, AVG(KPI_INVENTORY_DAYS) AS KPI_INVENTORY_DAYS, AVG(KPI_FABRIC_UTILIZATION) AS KPI_FABRIC_UTILIZATION, AVG(KPI_TRIM_AVAILABILITY) AS KPI_TRIM_AVAILABILITY, AVG(KPI_IMPORT_DEPENDENCY) AS KPI_IMPORT_DEPENDENCY FROM RAW.FABRIC_SHIPMENTS),
     en AS (SELECT SUM(KPI_ACTIVE_SUPPLIERS) AS KPI_ACTIVE_SUPPLIERS FROM RAW.SUPPLIERS)
  SELECT 1 AS SORT_ORDER, 'Fabric On-Time' AS TITLE, KPI_FABRIC_ON_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FABRIC_ON_TIME)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Active Suppliers' AS TITLE, KPI_ACTIVE_SUPPLIERS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_SUPPLIERS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Lead Time (Avg)' AS TITLE, KPI_LEAD_TIME_AVG AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_LEAD_TIME_AVG)) AS DECIMAL(38,0))) || ' ' || 'days' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Inventory Days' AS TITLE, KPI_INVENTORY_DAYS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_INVENTORY_DAYS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Fabric Utilization' AS TITLE, KPI_FABRIC_UTILIZATION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FABRIC_UTILIZATION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Trim Availability' AS TITLE, KPI_TRIM_AVAILABILITY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_TRIM_AVAILABILITY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Import Dependency' AS TITLE, KPI_IMPORT_DEPENDENCY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_IMPORT_DEPENDENCY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
